### PR TITLE
Update GPG key

### PR DESCRIPTION
**Pull request by eheydrick**
Previous key expired in March.

### CODE REVIEW

**Comment by eheydrick** [comment]
Would be nice to see this merged as aptly won't unless without the new key.

**Comment by slyness** [comment]
Thanks @eheydrick you picked the right day to ping me. ;) Sorry for the delay. will merge and cut this asap.

**Comment by eheydrick** [comment]
Niiiiice, thanks!

**Comment by slyness** [comment]
it's in the wild. released with 0.2.8. Have a good weekend.

**Pull request merged**
